# Generated by Django 3.1.7 on 2021-08-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
                ('emailid', models.EmailField(max_length=20)),
                ('inbox', models.TextField(max_length=5000)),
            ],
        ),
    ]
