# Generated by Django 3.1.7 on 2021-08-27 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pofo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='emailid',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='fullname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
